from __future__ import annotations

STAGING_COLUMNS = [
    "Source_File",
    "Source_Row",
    "Organisation_Name",
    "Contact_Name",
    "Email",
    "Email_Alternatives",
    "Phone",
    "Phone_Alternatives",
    "Website",
    "Website_Alternatives",
    "LinkedIn",
    "Social_Media",
    "Role",
    "Organisation_Type",
    "Sector",
    "Location",
    "Address",
    "Description",
    "Status",
    "Notes",
    "Tags",
    "Responsible_Person",
    "Project_or_Event",
    "Last_Contact_Date",
    "Email_Count",
    "Direction",
    "Relationship_Strength",
    "Last_Subject_Line",
    "Source_Document",
    "Original_Contact_Info",
]

FILE_MAPPINGS = {
    "Add an organization to Berlin's circular ecosystem (Responses) - Form Responses 1.csv": {
        "Organisation_Name": "Name of organization/project",
        "Email": "Add your email in case we have clarification questions.",
        "Website": "What is your website address?",
        "Organisation_Type": "What type is the organization/project?",
        "Sector": "What field does the organization/project work in?",
        "Tags": "Add some tags to make finding the organisation easier.",
        "Description": "What does the organization/project do?",
        "Status": "I want to...",
        "Notes": "What are your improvement suggestions?",
    },
    "BuildSkills _ contact list  - CB contact list.csv": {
        "Organisation_Name": "ORGANISATION",
        "Contact_Name": "Contact person",
        "Email": "Email",
        "Website": "Website",
        "LinkedIn": "Linkedin",
        "Organisation_Type": "Type",
        "Notes": "Comments",
        "Responsible_Person": "Who sends",
    },
    "Circular City Challenge 2024 _  2023_Partner list .xlsx - Kommunale Partner .csv": {
        "Organisation_Name": "Organisation",
        "Contact_Name": "Name ",
        "Email": "Email",
        "Website": "Website",
        "Location": "Location",
        "Organisation_Type": "Partner Type",
        "Status": "Status",
        "LinkedIn": "LinkedIN",
        "Responsible_Person": "Contact of",
        "Notes": "City / District level",
    },
    "Circular City Guide 2023_Ideas_organisations_initiatives - List to use for the book.csv": {
        "Organisation_Name": "Organisation Name",
        "Contact_Name": "Kontakt",
        "Email": "Mail ",
        "Sector": "Sector",
        "Tags": "CE Strategy",
        "Status": "Final status",
        "Notes": "Dina's & Ari´s comments",
    },
    "Circular City Guide 2023_Ideas_organisations_initiatives - List.csv": {
        "Organisation_Name": "Organisation Name",
        "Contact_Name": "Kontakt",
        "Email": "Mail ",
        "Sector": "Sector",
        "Tags": "CE Strategy",
        "Status": "Final status",
        "Description": "Beschreibung der Initiative: Was ist das konkrete Angebot, das die Menschen in Berlin nutzen können?",
        "Location": "Wo findet man dich in Berlin? (Straße, Nummer, PLZ, Bezirk/Kiez)",
        "Notes": "Dina's & Ari´s comments",
        "Responsible_Person": "Contacted by",
    },
    "Circular Experiences - MASTER LIST.xlsx - NEW Projects to visit.csv": {
        "Organisation_Name": "PROJECT",
        "Contact_Name": "Contact Person",
        "Email": "Email",
        "Phone": "Telefon",
        "Address": "Adresse",
        "Sector": "Focus",
        "Notes": "Notes",
    },
    "Contact list for the cooperation partners in food MASTER FILE - Food related stakeholders.csv": {
        "Organisation_Name": "Organization",
        "Organisation_Type": "Organization Type",
        "Original_Contact_Info": "Contact name and position",
        "Notes": "Comments",
        "Responsible_Person": "Responsible for contact",
        "Status": "Status",
        "Project_or_Event": "Potential collaborations / Project",
    },
    "Copy of T&S Contact lists for WS & WB - CB contacts.csv": {
        "Organisation_Name": "Name",
        "Website": "Website",
        "Email": "Email",
        "Location": "Location",
        "Description": "Description of Technology",
        "Sector": "Technology",
        "Responsible_Person": "Whose contact?",
        "Notes": "Note (if any follow ups or requests)",
    },
    "Copy of T&S Contact lists for WS & WB - Wista Adlershof.csv": {
        "Organisation_Name": "Name",
        "Website": "Website",
        "Email": "Email ",
        "Phone": "Phone ",
        "Original_Contact_Info": "Contact Info",
        "Description": "Description of Technology",
        "Sector": "Technology",
        "Notes": "Note (if any follow ups or requests)",
    },
    "FINAL ABCircular Construction + Textiles 2025 - FINAL BTH Model Construction.csv": {
        "Organisation_Name": "Entity Name",
        "Organisation_Type": "Type of Organisation",
        "Location": "Regional Focus",
        "Sector": "Lifecycle Phase",
        "Tags": "Circular Economy Category / Practices / Specifics",
        "Description": "Short Description of Organisation's activities",
        "Address": "Address and Location",
        "Website": "Website",
        "Email": "Email",
        "Phone": "Telephone",
        "Contact_Name": "Contact Person",
        "Notes": "Case Studies",
    },
    "FINAL ABCircular Construction + Textiles 2025 - FINAL BTH Model Textiles.csv": {
        "Organisation_Name": "Entity Name",
        "Organisation_Type": "Type of Organisation",
        "Location": "Regional Focus",
        "Sector": "Lifecycle Phase",
        "Tags": "Circular Economy Category / Practices / Specifics",
        "Description": "Short Description of Organisation's activities",
        "Address": "Address and Location",
        "Website": "Website",
        "Email": "Email",
        "Phone": "Telephone",
        "Contact_Name": "Contact Person",
        "Notes": "Case Studies",
    },
    "List of Potential Participants (Roundtable _ Zalando Workshop) Ghana 2024 - ORIGINAL.csv": {
        "Contact_Name": " Name",
        "Role": "Role",
        "Organisation_Name": "Organisation",
        "Email": "Email",
        "Status": "Participation",
        "Responsible_Person": "Contact Person",
        "Notes": "Notes",
    },
    "List of Potential Participants (Roundtable _ Zalando Workshop) Ghana 2024 - ROUNDTABLE.csv": {
        "Contact_Name": " Name",
        "Role": "Role",
        "Organisation_Name": "Organisation",
        "Original_Contact_Info": "Contact  (email / phone)",
        "Notes": "Additional Notes",
    },
    "List of Potential Participants (Roundtable _ Zalando Workshop) Ghana 2024 - Zalando.csv": {
        "Contact_Name": " Name",
        "Role": "Role",
        "Email": "Email",
        "Organisation_Name": "__CONSTANT__:Zalando",
        "Tags": "GROUP",
    },
    "List of contacts - ARCA - Multiplicator Open Call for Designer (Textile) 2025 - Sheet1.csv": {
        "Contact_Name": "Name ",
        "Organisation_Name": "Organisation",
        "Role": "Role",
        "Location": "Location",
        "Original_Contact_Info": "Email / phone",
        "Responsible_Person": "Contact Person",
    },
    "Overview tech communities_accelerators_Tender launch - Sheet1.csv": {
        "Organisation_Name": "Institution",
        "Contact_Name": "Contact",
        "Email": "Mail",
        "Website": "URL",
        "Status": "Status quo",
    },
    "PARTICIPANTS LIST__online workshop_Ghana Exchange 2024 - Confirmed participants.csv": {
        "Contact_Name": "Full Name",
        "Organisation_Name": "Name of your organisation",
        "Role": "Your role in the organisation",
        "Email": "Email Address",
        "Location": "Which country are you based in?",
    },
    "PARTICIPANTS LIST__online workshop_Ghana Exchange 2024 - Invitations.csv": {
        "Contact_Name": "PARTICIPANTS ",
        "Role": "ROLE",
        "Organisation_Name": "ORGANISATION",
        "Location": "COUNTRY",
        "Responsible_Person": "Who",
        "Email": "Email",
        "Status": "Status",
    },
    "Partner_LOOPTOPIA - OLD_Programpartner.csv": {
        "Organisation_Name": "Company/ Organization",
        "Contact_Name": "Name",
        "Original_Contact_Info": "Contact",
        "Responsible_Person": "CB Contact person",
        "Status": "Status",
        "Notes": "Notes",
    },
    "Pilot Partner & Stakeholder - SOLSTICE 2025-26 - 1. Repair Partner.csv": {
        "Organisation_Name": "Organisation",
        "Organisation_Type": "Stakeholder Group",
        "Status": "Status",
        "Sector": "Expertise",
        "Contact_Name": "Contact",
        "Original_Contact_Info": "Mail / Phone",
        "Website": "website",
        "Location": "District",
        "Notes": "Challenges",
    },
    "Pilot Partner & Stakeholder - SOLSTICE 2025-26 - 2. Sponsoring Partner.csv": {
        "Organisation_Name": "Organisation",
        "Organisation_Type": "Stakeholder Group",
        "Status": "Status",
        "Contact_Name": "Contact",
        "Original_Contact_Info": "Mail / Phone",
        "Website": "website",
        "Notes": "Sponsoring",
    },
    "Pilot Partner & Stakeholder - SOLSTICE 2025-26 - 3. Pop-Up Partner.csv": {
        "Organisation_Name": "Organisation",
        "Organisation_Type": "Stakeholder Group",
        "Role": "Pop-Up Role",
        "Contact_Name": "Contact",
        "Original_Contact_Info": "Mail / Phone",
        "Website": "website",
        "Social_Media": "Social Media",
    },
    "Pilot Partner & Stakeholder - SOLSTICE 2025-26 - 4. Pop-Up Locations.csv": {
        "Organisation_Name": "Organisation",
        "Organisation_Type": "Stakeholder Group",
        "Status": "Status",
        "Sector": "Expertise",
        "Contact_Name": "Contact",
        "Original_Contact_Info": "Mail / Phone",
        "Role": "Role in pilot",
        "Notes": "Info",
        "Website": "website",
        "Location": "District",
    },
    "Pilot Partner & Stakeholder - SOLSTICE 2025-26 - 5. Stakeholder Sharing Campaign.csv": {
        "Organisation_Name": "Organisation",
        "Organisation_Type": "Stakeholder Group",
        "Contact_Name": "Contact",
        "Original_Contact_Info": "Mail / Phone",
        "Notes": "Info ",
        "Website": "Link",
        "Social_Media": "Media",
        "Status": "Shared?",
    },
    "Pilot Partner & Stakeholder - SOLSTICE 2025-26 - 7. Lokale Ankerpunkte.csv": {
        "Organisation_Name": "Organisation",
        "Location": "District",
        "Notes": "Info",
        "Status": "Status",
        "Social_Media": "Media",
        "Organisation_Type": "Type of Stakheolder",
        "Contact_Name": "Contact",
        "Original_Contact_Info": "Mail / Phone",
        "Website": "website",
    },
    "Pilot Partner & Stakeholder - SOLSTICE 2025-26 - External Events to promote Repair Deal.csv": {
        "Project_or_Event": "Event ",
        "Description": "What is it about?",
        "Location": "Where is it?",
        "Status": "Status",
        "Original_Contact_Info": "Contact",
        "Website": "Link",
        "Notes": "What do we do to reach target?",
    },
    "IMPORT_SANDBOX_CRM contacts.xlsx - CRM Log (Dinas gmail contacts).csv": {
        "Status": "Status",
        "Contact_Name": "Name",
        "Email": "Email",
        "Organisation_Name": "Organisation",
        "Last_Contact_Date": "Last Contact (Date)",
        "Email_Count": "# of Emails",
        "Direction": "Direction",
        "Relationship_Strength": "Relationship Strength",
        "Last_Subject_Line": "Last Subject Line (Optional but helpful)",
        "Source_Document": "Source document",
        "Organisation_Type": "Org Type",
    },
}

SPECIAL_FILE_CONFIG = {
    "Construction account management list - Construction account management.csv": {
        "header_row": 12,
        "mapping": {
            "Status": "reviewed",
            "Organisation_Name": "Name",
            "Organisation_Type": "Type",
            "Location": "Geography",
            "Website": "website",
            "Contact_Name": "Contact",
            "Role": "Role and department",
            "Responsible_Person": "Contact of",
            "LinkedIn": "Linkedin",
            "Email": "Email",
            "Description": "Practical relevance in CC (e.g. project work, materials)",
            "Notes": "Trusted contact",
        },
    },
    "February 2026 export-circular-berlin-ecosystem-21.xlsx - Elements.csv": {
        "header_row": 1,
        "mapping": {
            "Organisation_Name": "Label",
            "Organisation_Type": "Type",
            "Website": "Website",
            "Description": "New Description",
            "Status": "Dina (Status) (to remove / to merge / to update content)",
        },
    },
    "List of funding opportunities.xlsx - Organizations.csv": {
        "header_row": 1,
        "mapping": {
            "Organisation_Name": "Organization / Funding Name",
            "Responsible_Person": "Funder",
            "Status": "Active",
            "Description": "Funding focus (text)",
            "Organisation_Type": "Organization type",
            "Location": "Based in",
            "Sector": "Sector",
            "Contact_Name": "Contact person",
            "Original_Contact_Info": "Email / phone",
            "Website": "Website",
            "Notes": "Comments",
        },
    },
    "Pilot Partner & Stakeholder - SOLSTICE 2025-26 - 6. Botschafter_innen.csv": {
        "header_row": 1,
        "mapping": {
            "Contact_Name": "Name",
            "Social_Media": "Instagram",
            "Email": "Mail",
            "Status": "Zusage?",
            "Notes": "Eingeladen Pop Up 2 per Mail",
        },
    },
}
